var baseCards = require('./baseCards');
var humCard = require('../humCard');

var HumAnswerCards = function() {
    baseCards.BaseCards.call(this);
    this.data = [
"A foul mouth",
"A Gypsy curse",
"A moment of silence",
"A sausage festival",
"An honest cop with nothing left to lose",
"Famine",
"Flesh-eating bacteria",
"Letting yourself go",
"Not giving a shit about the Third World",
"Sexting",
"Garth Brooks",
"Porn stars",
"Raping and pillaging",
"72 virgins",
"A drive-by shooting",
"A time-travel paradox",
"Authentic Mexican cuisine",
"Bling",
"Consultants",
"Crippling debt",
"Daddy issues",
"Donald Trump",
"Dropping a chandelier on your enemies and riding the rope up",
"Former President George W Bush",
"Full frontal nudity",
"Hormone injections",
"Laying an egg",
"Mountain Dew Code Red",
"Pretending to care",
"Public ridicule",
"Sharing needles",
"Stunt doubles",
"The inevitable heat death of the universe",
"The miracle of childbirth",
"The Rapture",
"Whipping it out",
"White privilege",
"Wifely duties",
"The Hamburglar",
"AXE Body Spray",
"The Blood of Christ",
"Hunting accidents",
"BATMAN!!!",
"Agriculture",
"A robust mongoloid",
"Natural selection",
"Coat hanger abortions",
"Eating all of the cookies before the AIDS bake-sale",
"Michelle Obama\'s arms",
"The World of Warcraft",
"Swooping",
"Obesity",
"The People\'s Elbow",
"Lockjaw",
"A mating display",
"Testicular torsion",
"All-you-can-eat shrimp for $499",
"Domino\'s Oreo Dessert Pizza",
"Kanye West",
"Bananas in Pajamas",
"Raptor attacks",
"Taking off your shirt",
"Smegma",
"Alcoholism",
"A middle-aged man on roller skates",
"Will Smith",
"Bingeing and purging",
"Oversized lollipops",
"Self-loathing",
"Children on leashes",
"Half-assed foreplay",
"The Holy Bible",
"German dungeon porn",
"Being on fire",
"A neglected Tamagotchi",
"Gandhi",
"Leaving an awkward voicemail",
"Uppercuts",
"Douchebags on their iPhones",
"An erection that lasts longer than four hours",
"My genitals",
"Picking up girls at the abortion clinic",
"Science",
"Not reciprocating oral sex",
"Flightless birds",
"A good sniff",
"Waterboarding",
"A balanced breakfast",
"Historically black colleges",
"Those times when you get sand in your vagina",
"The Make-A-Wish Foundation",
"A clandestine butt scratch",
"Passive-aggression",
"The Chinese gymnastics team",
"Marky Mark and the Funky Bunch",
"Peeing a little bit",
"Sobbing into a Hungry-Man Frozen Dinner",
"Nocturnal emissions",
"The Jews",
"My humps",
"Powerful thighs",
"Winking at old people",
"Mr Clean, right behind you",
"Making sex at her",
"Sexual tension",
"The forbidden fruit",
"Skeletor",
"Fancy Feast",
"Being rich",
"Sweet, sweet vengeance",
"Republicans",
"A gassy antelope",
"Natalie Portman",
"Copping a feel",
"Kamikaze pilots",
"Sean Connery",
"The homosexual agenda",
"The hardworking Mexican",
"A falcon with a cap on its head",
"Altar boys",
"The Kool-Aid Man",
"Getting so angry that you pop a boner",
"Free samples",
"A big hoopla about nothing",
"Doing the right thing",
"The Three-Fifths compromise",
"Lactation",
"World peace",
"RoboCop",
"Have some more kugel",
"Justin Bieber",
"Oompa-Loompas",
"Inappropriate yodeling",
"Puberty",
"Ghosts",
"An asymmetric boob job",
"Vigorous jazz hands",
"Fingering",
"Glenn Beck catching his scrotum on a curtain hook",
"GoGurt",
"Police brutality",
"John Wilkes Booth",
"Preteens",
"Scalping",
"Stifling a giggle at the mention of Hutus and Tutsis",
"Tweeting",
"Darth Vader",
"A sad handjob",
"Twinkies",
"Substitute teachers",
"Adderall",
"Ring Pops",
"Tasteful sideboob",
"Panda sex",
"An icepick lobotomy",
"Tom Cruise",
"Mouth herpes",
"Sperm whales",
"Homeless people",
"Third base",
"Incest",
"Cookie Monster devouring the Eucharist wafers",
"A mime having a stroke",
"Hulk Hogan",
"God",
"Scrubbing under the folds",
"Golden showers",
"Emotions",
"Licking things to claim them as your own",
"Pabst Blue Ribbon",
"The placenta",
"Spontaneous human combustion",
"Friends with benefits",
"Finger painting",
"Old-people smell",
"Dying of dysentery",
"A cartoon camel enjoying the smooth, refreshing taste of a cigarette",
"A Super Soaker full of cat pee",
"Aaron Burr",
"Cuddling",
"Shorties and blunts",
"Cockfights",
"Friendly fire",
"Ronald Reagan",
"A disappointing birthday party",
"A sassy black woman",
"Mathletes",
"A tiny horse",
"William Shatner",
"Riding off into the sunset",
"An M Night Shyamalan plot twist",
"Jew-fros",
"Mutually-assured destruction",
"Pedophiles",
"Yeast",
"Grave robbing",
"Eating the last known bison",
"Catapults",
"Poor people",
"Forgetting the Alamo",
"The Hustle",
"The Force",
"Wiping her butt",
"Intelligent design",
"Loose lips",
"AIDS",
"Pictures of boobs",
"The Übermensch",
"Sarah Palin",
"American Gladiators",
"Getting really high",
"Scientology",
"Penis envy",
"Praying the gay away",
"Frolicking",
"Two midgets shitting into a bucket",
"The KKK",
"Genghis Khan",
"PCP",
"Serfdom",
"Stranger danger",
"Faith healing",
"Shaquille O\'Neal\'s acting career",
"Prancing",
"The Thong Song",
"Overcompensation",
"Pixelated bukkake",
"A lifetime of sadness",
"Racism",
"Dwarf tossing",
"Sunshine and rainbows",
"A monkey smoking a cigar",
"Flash flooding",
"Lance Armstrong\'s missing testicle",
"Dry heaving",
"The terrorists",
"Britney Spears at 55",
"Attitude",
"Tiger Woods",
"Leprosy",
"Gloryholes",
"Nipple blades",
"The heart of a child",
"Puppies!",
"Waking up half-naked in a Denny\'s parking lot",
"Dental dams",
"Toni Morrison\'s vagina",
"The taint; the grundle; the fleshy fun-bridge",
"Active listening",
"Ethnic cleansing",
"That one gay Teletubby",
"The invisible hand",
"Waiting 'til marriage",
"Muzzy",
"Heath Ledger",
"Re-gifting",
"Autocannibalism",
"Impotence",
"My collection of high-tech sex toys",
"The Pope",
"White people",
"Tentacle porn",
"Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts",
"Too much hair gel",
"Seppuku",
"Same-sex ice dancing",
"Cheating in the Special Olympics",
"This answer is postmodern",
"Keanu Reeves",
"Sean Penn",
"Nickelback",
"A look-see",
"Pooping back and forth Forever",
"Menstruation",
"Kids with ass cancer",
"A salty surprise",
"The South",
"The violation of our most basic human rights",
"YOU MUST CONSTRUCT ADDITIONAL PYLONS",
"Date rape",
"Being fabulous",
"Necrophilia",
"Centaurs",
"Bill Nye the Science Guy",
"Black people",
"Chivalry",
"Lunchables",
"Bitches",
"The profoundly handicapped",
"Heartwarming orphans",
"Dave Matthews Band",
"Fiery poops",
"Another goddamn vampire movie",
"Tangled Slinkys",
"Keeping Christ in Christmas",
"Estrogen",
"A zesty breakfast burrito",
"That thing that electrocutes your abs",
"Passing a kidney stone",
"A bleached asshole",
"Michael Jackson",
"Cybernetic enhancements",
"Guys who don\'t call",
"Smallpox blankets",
"Masturbation",
"Classist undertones",
"Queefing",
"Concealing a boner",
"Edible underpants",
"Viagra",
"Eastern European Turbo-Folk music",
"Muhammad (Praise Be Unto Him)",
"Surprise sex!",
"Five-Dollar Footlongs",
"Drinking alone",
"Dick fingers",
"Multiple stab wounds",
"Soiling oneself",
"Child abuse",
"Anal beads",
"Civilian casualties",
"Pulling out",
"Robert Downey, Jr",
"Horse meat",
"A really cool hat",
"Kim Jong-il",
"A stray pube",
"Jewish fraternities",
"The token minority",
"Doin\' it in the butt",
"Feeding Rosie O\'Donnell",
"Teaching a robot to love",
"A can of whoop-ass",
"A windmill full of corpses",
"Count Chocula",
"Wearing underwear inside-out to avoid doing laundry",
"A grande sugar-free iced soy caramel macchiato",
"The glass ceiling",
"A cooler full of organs",
"The American Dream",
"Keg stands",
"When you fart and a little bit comes out",
"Take-backsies",
"Dead babies",
"Foreskin",
"Saxophone solos",
"Italians",
"A fetus",
"Bestiality",
"Dick Cheney",
"Amputees",
"Eugenics",
"My relationship status",
"Christopher Walken",
"Bees?",
"Harry Potter erotica",
"College",
"Getting drunk on mouthwash",
"Nazis",
"8 oz of sweet Mexican black-tar heroin",
"Stephen Hawking talking dirty",
"Dead parents",
"Object permanence",
"Opposable thumbs",
"Racially-biased SAT questions",
"Crumpets with the Queen",
"Chainsaws for hands",
"The deformed",
"Child beauty pageants",
"Explosions",
"Sniffing glue",
"Glenn Beck being harried by a swarm of buzzards",
"Repression",
"Roofies",
"Mr Snuffleupagus",
"Assless chaps",
"A murder most foul",
"Giving 110%",
"Her Royal Highness, Queen Elizabeth II",
"The Trail of Tears",
"Being marginalized",
"Goblins",
"Hope",
"Dr Martin Luther King, Jr",
"A micropenis",
"My soul",
"A hot mess",
"Vikings",
"Hot people",
"Seduction",
"An Oedipus complex",
"Geese",
"Global warming",
"New Age music",
"Hot Pockets",
"Making a pouty face",
"Vehicular manslaughter",
"Women\'s suffrage",
"Flavored condoms",
"Judge Judy",
"African children",
"The Virginia Tech Massacre",
"Barack Obama",
"Asians who aren\'t good at math",
"Elderly Japanese men",
"Exchanging pleasantries",
"Heteronormativity",
"Parting the Red Sea",
"Arnold Schwarzenegger",
"Road head",
"Spectacular abs",
"Figgy pudding",
"Drum circles",
"A bag of magic beans",
"A LAN party",
"My sex life",
"Auschwitz",
"A snapping turtle biting the tip of your penis",
"A thermonuclear detonation",
"The clitoris",
"The Big Bang",
"Land mines",
"Friends who eat all the snacks",
"Goats eating cans",
"The Dance of the Sugar Plum Fairy",
"Jerking off into a pool of children\'s tears",
"Man meat",
"Me time",
"The Underground Railroad",
"Poorly-timed Holocaust jokes",
"A sea of troubles",
"Lumberjack fantasies",
"(I am doing Kegels right now)",
"Women in yogurt commercials",
"Abstinence",
"Being a motherfucking sorcerer",
"Genital piercings",
"Passable transvestites",
"Sexy pillow fights",
"Balls",
"Grandma",
"Friction",
"Party poopers",
"Farting and walking away",
"Being a dick to children",
"Booby-trapping the house to foil burglars",
"The Tempur-Pedic Swedish Sleep System",
"Dying",
"Hurricane Katrina",
"The gays",
"The folly of man",
"Men",
"The Amish",
"Pterodactyl eggs",
"Team-building exercises",
"A brain tumor",
"Cards Against Humanity",
"Fear itself",
"A vajazzled vagina",
"The milk man",
"A beached whale",
"A big black dick",
"A bloody pacifier",
"A crappy little hand",
"A low standard of living",
"A nuanced critique",
"A panty raid",
"A passionate Latino lover",
"A rival dojo",
"A web of lies",
"A woman scorned",
"An atomic wedgie",
"Apologizing",
"Appreciative snapping",
"Ashton Kutcher",
"Beating your wives",
"Being a dinosaur",
"Blaxploitation",
"Bosnian chicken farmers",
"Breaking nip slip news",
"Carnies",
"Coughing into a vagina",
"Cutting",
"Dancing with a broom",
"Deflowering the princess",
"Dorito breath",
"Eating an albino",
"Eating all of the cookies before the AIDS bake-sale",
"Enormous Scandinavian women",
"Fabricating statistics",
"Finding a skeleton",
"Gandalf",
"Genetically-engineered super-soldiers",
"George Clooney\'s musk",
"Getting abducted by Peter Pan",
"Getting in her pants, politely",
"Gladiatorial combat",
"Good grammar",
"Hipsters",
"Historical revisionism",
"Insatiable bloodlust",
"Jafar",
"Jean-Claude Van Damme",
"Just the tip",
"Ladles",
"Leveling up",
"Literally eating shit",
"Making the penises kiss",
"Media coverage",
"Medieval Times Dinner & Tournament",
"Moral ambiguity",
"My machete",
"NOOOOOOOOOO!!!",
"Ominous background music",
"Overpowering your father",
"Pistol whipping a hostage",
"Quiche",
"Quivering jowls",
"Revenge fucking",
"Ripping into a man\'s chest and pulling out his still-beating heart",
"Ryan Gosling riding in on a white horse",
"Santa Claus",
"Scrotum tickling",
"Sexual humiliation",
"Sexy Siamese twins",
"Slow motion",
"Space muffins",
"Statistically validated stereotypes ",
"Sudden poop explosion disease",
"The boners of the elderly",
"The economy",
"The Fanta girls",
"The Gulags",
"The harsh light of day",
"The hiccups",
"The shambling corpse of Larry King",
"The four arms of Vishnu",
"This guy!",
"Tripping balls",
"Words, words, words",
"Zeus\'s sexual appetite"
    ];   

    this.createArray();
}

HumAnswerCards.prototype = new baseCards.BaseCards;

HumAnswerCards.prototype.getCard = function(i) {
    var text = this.cardArray[i];
//    console.log('text: ' + text);
    return new humCard.HumCard(i, this.cardArray[i]);
}

exports.HumAnswerCards = HumAnswerCards;
